### ISSUE TITLE
Initiative Tracker

### ISSUE THREAD

**Issue by Blujeansonfire** [CrescentTRPG/Crescent-v2#48]
- [ ] Characters see initiative tracker appear on adventure page if option is toggled on
- [ ] Characters can modify the initiative tracker (if option is turned on)
- [ ] initiative tracker can be sorted desc, hit next turn, individual items of the initiative tracker can be dragged and dropped around
- [ ] Game master has options to add characters + tabbed monsters to the initiative tracker, add chosen individuals, and add generic combatants.  Monsters / NPC's auto roll initiative, (it can be edited), characters have the option to auto roll for them or let characters roll and edit it themselves
- [ ] items in initiative tracker can be removed
- [ ] items in initiative tracker can be disabled and re-enabled with a toggle, enabled by default
- [ ] all items in initiative tracker can be cleared with a clear button
